version: '3.8'
services:
  node-dev:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: node-dev
    ports:
      - "${NODE_HOST_PORT}:${NODE_CONTAINER_PORT}"
    volumes:
      - "${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}"
    tty: true
    environment:
      - NVM_DIR=/usr/local/nvm
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
